"""add search console data foundation

Revision ID: 0e94a7f929dd
Revises: 1e68d07a418b
Create Date: 2026-09-06 23:39:12.841899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e94a7f929dd'
down_revision: Union[str, Sequence[str], None] = '1e68d07a418b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_console_import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_uri', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dimensions_json', sa.Text(), nullable=False),
    sa.Column('import_identity_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('page_rows_received', sa.Integer(), nullable=True),
    sa.Column('query_rows_received', sa.Integer(), nullable=True),
    sa.Column('page_rows_upserted', sa.Integer(), nullable=True),
    sa.Column('query_rows_upserted', sa.Integer(), nullable=True),
    sa.Column('response_snapshot', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_console_import_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_search_console_import_runs_idempotency_key')
    )
    with op.batch_alter_table('search_console_import_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_console_import_runs_import_identity_hash'), ['import_identity_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_console_import_runs_property_uri'), ['property_uri'], unique=False)

    op.create_table('search_console_page_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_uri', sa.String(length=255), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('page', sa.String(length=2048), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('source_import_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_import_run_id'], ['search_console_import_runs.id'], name=op.f('fk_search_console_page_daily_source_import_run_id_search_console_import_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_console_page_daily')),
    sa.UniqueConstraint('property_uri', 'metric_date', 'page', name='uq_search_console_page_daily_property_date_page')
    )
    with op.batch_alter_table('search_console_page_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_console_page_daily_source_import_run_id'), ['source_import_run_id'], unique=False)

    op.create_table('search_console_query_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_uri', sa.String(length=255), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('page', sa.String(length=2048), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('source_import_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_import_run_id'], ['search_console_import_runs.id'], name=op.f('fk_search_console_query_daily_source_import_run_id_search_console_import_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_console_query_daily')),
    sa.UniqueConstraint('property_uri', 'metric_date', 'page', 'query', name='uq_search_console_query_daily_property_date_page_query')
    )
    with op.batch_alter_table('search_console_query_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_console_query_daily_source_import_run_id'), ['source_import_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_console_query_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_console_query_daily_source_import_run_id'))

    op.drop_table('search_console_query_daily')
    with op.batch_alter_table('search_console_page_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_console_page_daily_source_import_run_id'))

    op.drop_table('search_console_page_daily')
    with op.batch_alter_table('search_console_import_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_console_import_runs_property_uri'))
        batch_op.drop_index(batch_op.f('ix_search_console_import_runs_import_identity_hash'))

    op.drop_table('search_console_import_runs')
    # ### end Alembic commands ###
