"""add keyword_signals and keyword_score_signals

Revision ID: 1689a1b083a8
Revises: ca2a50f798ec
Create Date: 2026-08-27 16:12:55.047636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1689a1b083a8'
down_revision: Union[str, Sequence[str], None] = 'ca2a50f798ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('normalized_value', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('normalized_value BETWEEN 0 AND 100', name=op.f('ck_keyword_signals_normalized_value_range')),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_keyword_signals_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_signals'))
    )
    with op.batch_alter_table('keyword_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_signals_component'), ['component'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_signals_keyword_id'), ['keyword_id'], unique=False)

    op.create_table('keyword_score_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_score_id', sa.Integer(), nullable=False),
    sa.Column('keyword_signal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_score_id'], ['keyword_scores.id'], name=op.f('fk_keyword_score_signals_keyword_score_id_keyword_scores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_signal_id'], ['keyword_signals.id'], name=op.f('fk_keyword_score_signals_keyword_signal_id_keyword_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_score_signals')),
    sa.UniqueConstraint('keyword_score_id', 'keyword_signal_id', name='score_signal')
    )
    with op.batch_alter_table('keyword_score_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_score_signals_keyword_score_id'), ['keyword_score_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_keyword_score_signals_keyword_signal_id'), ['keyword_signal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_score_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_score_signals_keyword_signal_id'))
        batch_op.drop_index(batch_op.f('ix_keyword_score_signals_keyword_score_id'))

    op.drop_table('keyword_score_signals')
    with op.batch_alter_table('keyword_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_signals_keyword_id'))
        batch_op.drop_index(batch_op.f('ix_keyword_signals_component'))

    op.drop_table('keyword_signals')
    # ### end Alembic commands ###
