"""initial schema

Revision ID: 1892d6df0222
Revises: 
Create Date: 2026-08-27 15:18:56.413646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1892d6df0222'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('commission_type', sa.String(length=50), nullable=True),
    sa.Column('commission_value', sa.Float(), nullable=True),
    sa.Column('landing_page_url', sa.String(length=1024), nullable=True),
    sa.Column('tracking_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affiliate_programs'))
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords'))
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_keyword'), ['keyword'], unique=True)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('wordpress_post_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_articles_keyword_id_keywords'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles'))
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=True)

    op.create_table('article_affiliate_programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('affiliate_program_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_program_id'], ['affiliate_programs.id'], name=op.f('fk_article_affiliate_programs_affiliate_program_id_affiliate_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_affiliate_programs_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_affiliate_programs')),
    sa.UniqueConstraint('article_id', 'affiliate_program_id', name='article_program')
    )
    with op.batch_alter_table('article_affiliate_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_affiliate_programs_affiliate_program_id'), ['affiliate_program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_affiliate_programs_article_id'), ['article_id'], unique=False)

    op.create_table('article_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('average_position', sa.Float(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_metrics_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_metrics')),
    sa.UniqueConstraint('article_id', 'metric_date', 'provider', name='article_date_provider')
    )
    with op.batch_alter_table('article_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_metrics_article_id'), ['article_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_sources_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_article_id'), ['article_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_article_id'))

    op.drop_table('sources')
    with op.batch_alter_table('article_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_metrics_article_id'))

    op.drop_table('article_metrics')
    with op.batch_alter_table('article_affiliate_programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_affiliate_programs_article_id'))
        batch_op.drop_index(batch_op.f('ix_article_affiliate_programs_affiliate_program_id'))

    op.drop_table('article_affiliate_programs')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_slug'))

    op.drop_table('articles')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_keyword'))

    op.drop_table('keywords')
    op.drop_table('affiliate_programs')
    # ### end Alembic commands ###
