"""add wordpress_draft_runs

Revision ID: 2b8c28dfb5e9
Revises: 71fe1f7da534
Create Date: 2026-09-04 15:45:41.959085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b8c28dfb5e9'
down_revision: Union[str, Sequence[str], None] = '71fe1f7da534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordpress_draft_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('source_promotion_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('target_base_url', sa.String(length=1024), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint_path', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('request_identity_hash', sa.String(length=64), nullable=False),
    sa.Column('target_request_identity_hash', sa.String(length=64), nullable=False),
    sa.Column('canonical_body_hash', sa.String(length=64), nullable=False),
    sa.Column('canonical_meta_hash', sa.String(length=64), nullable=False),
    sa.Column('renderer_version', sa.String(length=40), nullable=False),
    sa.Column('rendered_content_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('wordpress_post_id', sa.String(length=64), nullable=True),
    sa.Column('wordpress_post_status', sa.String(length=40), nullable=True),
    sa.Column('wordpress_post_url', sa.Text(), nullable=True),
    sa.Column('response_snapshot', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_wordpress_draft_runs_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_promotion_id'], ['article_draft_promotions.id'], name=op.f('fk_wordpress_draft_runs_source_promotion_id_article_draft_promotions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wordpress_draft_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_wordpress_draft_runs_idempotency_key')
    )
    with op.batch_alter_table('wordpress_draft_runs', schema=None) as batch_op:
        batch_op.create_index('ix_wordpress_draft_runs_article_created_id', ['article_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wordpress_draft_runs_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wordpress_draft_runs_source_promotion_id'), ['source_promotion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wordpress_draft_runs_target_request_identity_hash'), ['target_request_identity_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordpress_draft_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wordpress_draft_runs_target_request_identity_hash'))
        batch_op.drop_index(batch_op.f('ix_wordpress_draft_runs_source_promotion_id'))
        batch_op.drop_index(batch_op.f('ix_wordpress_draft_runs_article_id'))
        batch_op.drop_index('ix_wordpress_draft_runs_article_created_id')

    op.drop_table('wordpress_draft_runs')
    # ### end Alembic commands ###
