"""add threads external observer tables

Revision ID: 2cfa0ccb2059
Revises: c4d2e8f1a9b3
Create Date: 2026-09-28 17:12:29.495019

T6.5B: 外の Threads を読むだけで観察した記録の表を 4 つ足すだけ (実行・外の投稿・観察ごとの値・
トレンドのトピック)。既存の表 (自分の提案・公開) は変えない。外の表示回数 (views) の列は持たない。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfa0ccb2059'
down_revision: Union[str, Sequence[str], None] = 'c4d2e8f1a9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads_external_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_post_key', sa.String(length=128), nullable=False),
    sa.Column('author_handle', sa.String(length=64), nullable=True),
    sa.Column('permalink', sa.String(length=512), nullable=True),
    sa.Column('post_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_hash', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('has_link', sa.Boolean(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('feature_version', sa.String(length=32), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_external_posts')),
    sa.UniqueConstraint('external_post_key', name='uq_threads_external_post_key')
    )
    with op.batch_alter_table('threads_external_posts', schema=None) as batch_op:
        batch_op.create_index('ix_threads_external_posts_author', ['author_handle'], unique=False)

    op.create_table('threads_observer_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source_types_json', sa.JSON(), nullable=True),
    sa.Column('item_limit', sa.Integer(), nullable=False),
    sa.Column('items_collected', sa.Integer(), nullable=False),
    sa.Column('items_rejected', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('collector_version', sa.String(length=64), nullable=False),
    sa.Column('selector_version', sa.String(length=64), nullable=False),
    sa.Column('artifacts_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_observer_runs'))
    )
    op.create_table('threads_trending_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('sample_post_count', sa.Integer(), nullable=False),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_trending_topics')),
    sa.UniqueConstraint('topic_name', 'source_type', name='uq_threads_trending_topic')
    )
    op.create_table('threads_external_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_query', sa.String(length=256), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('reposts', sa.Integer(), nullable=True),
    sa.Column('quotes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('body_hash', sa.String(length=64), nullable=True),
    sa.Column('extraction_status', sa.String(length=24), nullable=False),
    sa.Column('collector_version', sa.String(length=64), nullable=False),
    sa.Column('selector_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['threads_external_posts.id'], name=op.f('fk_threads_external_observations_post_id_threads_external_posts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['threads_observer_runs.id'], name=op.f('fk_threads_external_observations_run_id_threads_observer_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_external_observations'))
    )
    with op.batch_alter_table('threads_external_observations', schema=None) as batch_op:
        batch_op.create_index('ix_threads_external_observations_post', ['post_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_threads_external_observations_run', ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads_external_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_external_observations_run')
        batch_op.drop_index('ix_threads_external_observations_post')

    op.drop_table('threads_external_observations')
    op.drop_table('threads_trending_topics')
    op.drop_table('threads_observer_runs')
    with op.batch_alter_table('threads_external_posts', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_external_posts_author')

    op.drop_table('threads_external_posts')
    # ### end Alembic commands ###
