"""add threads publication trigger and gap override

Revision ID: 33d93394f342
Revises: b11082319d9d
Create Date: 2026-09-25 08:59:04.838422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d93394f342'
down_revision: Union[str, Sequence[str], None] = 'b11082319d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads_publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger', sa.String(length=16), server_default='manual', nullable=False))
        batch_op.add_column(sa.Column('gap_override_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gap_override_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads_publications', schema=None) as batch_op:
        batch_op.drop_column('gap_override_at')
        batch_op.drop_column('gap_override_reason')
        batch_op.drop_column('trigger')

    # ### end Alembic commands ###
