"""add change request approval workflow

Revision ID: 39c2fa18fb6a
Revises: e1b541ec6d33
Create Date: 2026-09-23 01:42:20.557405



C9:

- ``change_requests``: 候補 (C6/C7) と実際の記事変更のあいだに置く人間の承認境界。
  ``proposal_hash`` は提案の全内容から決まり、承認はこの値に結び付く。内容が変われば
  別 ``proposal_version`` の別レコードになるので、「あとで生成される文章」を
  承認してしまうことが構造的に起こらない。候補への不変リンク (engine / run /
  candidate id / dedupe key / priority / policy version / evidence) も凍結する。
- ``change_request_approvals``: 承認/却下の append-only な記録。
  ``approved_proposal_hash`` を持つので、古い承認が新しい提案へ移らない。
- ``change_applications``: 適用試行の append-only な記録。変更前の本文
  (``pre_change_body``) を必ず持つのでロールバックの起点になる。既存の managed な
  WordPress 更新経路が作った run の id (editorial revision / content update /
  reconciliation) を参照するだけで、更新スタックは新設しない。
- FK はいずれも RESTRICT。記事・承認・request は参照されている限り削除できない。
- backfill はしない。提案を作るまで 3 表とも空で、記事・WordPress・既存の取り込み
  には一切影響しない。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c2fa18fb6a'
down_revision: Union[str, Sequence[str], None] = 'e1b541ec6d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_engine', sa.String(length=16), nullable=False),
    sa.Column('source_candidate_run_id', sa.Integer(), nullable=True),
    sa.Column('source_candidate_id', sa.Integer(), nullable=True),
    sa.Column('source_candidate_dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('source_candidate_type', sa.String(length=64), nullable=True),
    sa.Column('source_candidate_priority', sa.String(length=16), nullable=True),
    sa.Column('source_policy_version', sa.String(length=64), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('target_article_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('proposal_version', sa.Integer(), nullable=False),
    sa.Column('proposal_hash', sa.String(length=64), nullable=False),
    sa.Column('expected_source_body_hash', sa.String(length=64), nullable=False),
    sa.Column('proposed_body_hash', sa.String(length=64), nullable=False),
    sa.Column('proposed_body', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('proposal_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source_engine IN ('seo', 'revenue', 'manual')", name=op.f('ck_change_requests_change_requests_engine')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_change_requests_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_article_id'], ['articles.id'], name=op.f('fk_change_requests_target_article_id_articles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_requests')),
    sa.UniqueConstraint('article_id', 'proposal_hash', name='uq_change_requests_article_proposal'),
    sa.UniqueConstraint('idempotency_key', name='uq_change_requests_idempotency_key')
    )
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_requests_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_change_requests_candidate', ['source_engine', 'source_candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_requests_proposal_hash'), ['proposal_hash'], unique=False)
        batch_op.create_index('ix_change_requests_status', ['status'], unique=False)

    op.create_table('change_request_approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('approved_proposal_hash', sa.String(length=64), nullable=False),
    sa.Column('approved_proposal_version', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('candidate_present_at_decision', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name=op.f('ck_change_request_approvals_change_approvals_decision')),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name=op.f('fk_change_request_approvals_change_request_id_change_requests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_request_approvals'))
    )
    with op.batch_alter_table('change_request_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_request_approvals_change_request_id'), ['change_request_id'], unique=False)
        batch_op.create_index('ix_change_request_approvals_request', ['change_request_id'], unique=False)

    op.create_table('change_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_request_id', sa.Integer(), nullable=False),
    sa.Column('change_request_approval_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('proposal_hash', sa.String(length=64), nullable=False),
    sa.Column('proposal_version', sa.Integer(), nullable=False),
    sa.Column('source_body_hash', sa.String(length=64), nullable=False),
    sa.Column('proposed_body_hash', sa.String(length=64), nullable=False),
    sa.Column('pre_change_body', sa.Text(), nullable=False),
    sa.Column('wordpress_post_id', sa.String(length=64), nullable=True),
    sa.Column('wordpress_pre_modified_gmt', sa.String(length=64), nullable=True),
    sa.Column('wordpress_post_modified_gmt', sa.String(length=64), nullable=True),
    sa.Column('editorial_revision_id', sa.Integer(), nullable=True),
    sa.Column('content_update_run_id', sa.Integer(), nullable=True),
    sa.Column('reconciliation_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_change_applications_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['change_request_approval_id'], ['change_request_approvals.id'], name=op.f('fk_change_applications_change_request_approval_id_change_request_approvals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.id'], name=op.f('fk_change_applications_change_request_id_change_requests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_applications')),
    sa.UniqueConstraint('idempotency_key', name='uq_change_applications_idempotency_key')
    )
    with op.batch_alter_table('change_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_applications_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_applications_change_request_id'), ['change_request_id'], unique=False)
        batch_op.create_index('ix_change_applications_request', ['change_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_change_applications_request')
        batch_op.drop_index(batch_op.f('ix_change_applications_change_request_id'))
        batch_op.drop_index(batch_op.f('ix_change_applications_article_id'))

    op.drop_table('change_applications')
    with op.batch_alter_table('change_request_approvals', schema=None) as batch_op:
        batch_op.drop_index('ix_change_request_approvals_request')
        batch_op.drop_index(batch_op.f('ix_change_request_approvals_change_request_id'))

    op.drop_table('change_request_approvals')
    with op.batch_alter_table('change_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_change_requests_status')
        batch_op.drop_index(batch_op.f('ix_change_requests_proposal_hash'))
        batch_op.drop_index('ix_change_requests_candidate')
        batch_op.drop_index(batch_op.f('ix_change_requests_article_id'))

    op.drop_table('change_requests')
    # ### end Alembic commands ###
