"""add threads publications

Revision ID: 3aa04575f329
Revises: b1c9ed9e3f71
Create Date: 2026-09-24 03:10:37.934301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa04575f329'
down_revision: Union[str, Sequence[str], None] = 'b1c9ed9e3f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads_publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('proposal_hash', sa.String(length=64), nullable=False),
    sa.Column('source_article_id', sa.Integer(), nullable=False),
    sa.Column('angle', sa.String(length=32), nullable=False),
    sa.Column('exact_published_text', sa.Text(), nullable=False),
    sa.Column('destination_url', sa.String(length=1024), nullable=True),
    sa.Column('threads_creation_id', sa.String(length=64), nullable=True),
    sa.Column('threads_media_id', sa.String(length=64), nullable=True),
    sa.Column('permalink', sa.String(length=1024), nullable=True),
    sa.Column('remote_timestamp', sa.String(length=64), nullable=True),
    sa.Column('remote_username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('reconciliation_required', sa.Boolean(), nullable=False),
    sa.Column('reconciliation_note', sa.Text(), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('publish_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'creating', 'container_created', 'publishing', 'published', 'failed', 'uncertain')", name=op.f('ck_threads_publications_threads_publications_status')),
    sa.ForeignKeyConstraint(['proposal_id'], ['threads_post_proposals.id'], name=op.f('fk_threads_publications_proposal_id_threads_post_proposals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_article_id'], ['articles.id'], name=op.f('fk_threads_publications_source_article_id_articles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_publications')),
    sa.UniqueConstraint('proposal_id', name='uq_threads_publications_proposal'),
    sa.UniqueConstraint('threads_media_id', name='uq_threads_publications_media')
    )
    with op.batch_alter_table('threads_publications', schema=None) as batch_op:
        batch_op.create_index('ix_threads_publications_status', ['status'], unique=False)

    op.create_table('threads_publication_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('threads_publication_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['threads_publication_id'], ['threads_publications.id'], name=op.f('fk_threads_publication_attempts_threads_publication_id_threads_publications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_publication_attempts'))
    )
    with op.batch_alter_table('threads_publication_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_threads_publication_attempts_pub', ['threads_publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads_publication_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_publication_attempts_pub')

    op.drop_table('threads_publication_attempts')
    with op.batch_alter_table('threads_publications', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_publications_status')

    op.drop_table('threads_publications')
    # ### end Alembic commands ###
