"""add threads insight snapshots

Revision ID: 3e397a01af66
Revises: 3aa04575f329
Create Date: 2026-09-24 03:29:22.128094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e397a01af66'
down_revision: Union[str, Sequence[str], None] = '3aa04575f329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads_insight_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('threads_publication_id', sa.Integer(), nullable=False),
    sa.Column('threads_media_id', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('age_hours', sa.Float(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('reposts', sa.Integer(), nullable=True),
    sa.Column('quotes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('missing_json', sa.JSON(), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['threads_publication_id'], ['threads_publications.id'], name=op.f('fk_threads_insight_snapshots_threads_publication_id_threads_publications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_insight_snapshots')),
    sa.UniqueConstraint('threads_publication_id', 'observed_at', name='uq_threads_insight_observation')
    )
    with op.batch_alter_table('threads_insight_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_threads_insight_snapshots_pub', ['threads_publication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads_insight_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_insight_snapshots_pub')

    op.drop_table('threads_insight_snapshots')
    # ### end Alembic commands ###
