"""add draft_generation_runs

Revision ID: 3e86dc460cd9
Revises: 539cdcb66b22
Create Date: 2026-08-28 19:36:53.497158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e86dc460cd9'
down_revision: Union[str, Sequence[str], None] = '539cdcb66b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_generation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_template_version', sa.String(length=40), nullable=False),
    sa.Column('prompt_builder_version', sa.String(length=40), nullable=False),
    sa.Column('prompt_package', sa.JSON(), nullable=False),
    sa.Column('prompt_input_hash', sa.String(length=64), nullable=False),
    sa.Column('rendered_prompt', sa.Text(), nullable=False),
    sa.Column('rendered_prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('editorial_overrides', sa.JSON(), nullable=False),
    sa.Column('generation_parameters', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('parsed_body', sa.Text(), nullable=True),
    sa.Column('parsed_meta_description', sa.String(length=400), nullable=True),
    sa.Column('generation_notes', sa.JSON(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_draft_generation_runs_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['draft_input_snapshots.id'], name=op.f('fk_draft_generation_runs_snapshot_id_draft_input_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_generation_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_draft_generation_runs_idempotency_key')
    )
    with op.batch_alter_table('draft_generation_runs', schema=None) as batch_op:
        batch_op.create_index('ix_draft_generation_runs_article_created_id', ['article_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_generation_runs_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_generation_runs_prompt_input_hash'), ['prompt_input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_generation_runs_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_generation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_generation_runs_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_draft_generation_runs_prompt_input_hash'))
        batch_op.drop_index(batch_op.f('ix_draft_generation_runs_article_id'))
        batch_op.drop_index('ix_draft_generation_runs_article_created_id')

    op.drop_table('draft_generation_runs')
    # ### end Alembic commands ###
