"""add growth handoff requests

Revision ID: 4fe83827d695
Revises: 74dbecaa4bb2
Create Date: 2026-09-29 23:02:07.890326

C9-B: 承認した Growth Action を既存の流れへ渡す手元の依頼 (Threads の生成・記事の計画・変更の準備) の
表を 1 つ足すだけ。既存の表は変えない。downgrade は、依頼の行が 1 行でもあれば止まる (記録が失われる
ため)。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe83827d695'
down_revision: Union[str, Sequence[str], None] = '74dbecaa4bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_handoff_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('lane', sa.String(length=24), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=True),
    sa.Column('source_growth_action_id', sa.Integer(), nullable=False),
    sa.Column('source_review_id', sa.Integer(), nullable=False),
    sa.Column('source_candidate_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('requested_angle', sa.String(length=32), nullable=True),
    sa.Column('frozen_json', sa.JSON(), nullable=False),
    sa.Column('frozen_hash', sa.String(length=64), nullable=False),
    sa.Column('generation_request_id', sa.String(length=64), nullable=True),
    sa.Column('downstream_type', sa.String(length=32), nullable=True),
    sa.Column('downstream_ids_json', sa.JSON(), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("change_type IS NULL OR change_type IN ('body_update', 'meta_description', 'affiliate_placement')", name=op.f('ck_growth_handoff_requests_growth_handoff_change_type')),
    sa.CheckConstraint("lane IS NULL OR lane IN ('regular', 'alternative_angle')", name=op.f('ck_growth_handoff_requests_growth_handoff_lane')),
    sa.CheckConstraint("status IN ('pending', 'claimed', 'proposal_created', 'approved', 'materialized', 'prepared', 'rejected', 'cancelled')", name=op.f('ck_growth_handoff_requests_growth_handoff_status')),
    sa.CheckConstraint("workflow IN ('threads_generation', 'article_planning', 'change_preparation')", name=op.f('ck_growth_handoff_requests_growth_handoff_workflow')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_growth_handoff_requests_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_growth_handoff_requests_keyword_id_keywords'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_growth_action_id'], ['growth_action_candidates.id'], name=op.f('fk_growth_handoff_requests_source_growth_action_id_growth_action_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_review_id'], ['growth_action_reviews.id'], name=op.f('fk_growth_handoff_requests_source_review_id_growth_action_reviews'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_handoff_requests')),
    sa.UniqueConstraint('idempotency_key', name='uq_growth_handoff_requests_idempotency')
    )
    with op.batch_alter_table('growth_handoff_requests', schema=None) as batch_op:
        batch_op.create_index('ix_growth_handoff_requests_article', ['article_id'], unique=False)
        batch_op.create_index('ix_growth_handoff_requests_workflow_status', ['workflow', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    rows = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM growth_handoff_requests")).scalar()
    if rows:
        raise RuntimeError(f"refusing to downgrade: {rows} growth handoff request(s) would be lost")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('growth_handoff_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_growth_handoff_requests_workflow_status')
        batch_op.drop_index('ix_growth_handoff_requests_article')

    op.drop_table('growth_handoff_requests')
    # ### end Alembic commands ###
