"""add draft_input_snapshots

Revision ID: 539cdcb66b22
Revises: ba2e8486248e
Create Date: 2026-08-28 17:29:01.689012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539cdcb66b22'
down_revision: Union[str, Sequence[str], None] = 'ba2e8486248e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_input_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_version', sa.String(length=32), nullable=False),
    sa.Column('builder_version', sa.String(length=64), nullable=False),
    sa.Column('plan_snapshot_origin', sa.String(length=64), nullable=False),
    sa.Column('primary_affiliate_program_id', sa.Integer(), nullable=True),
    sa.Column('comparison_program_ids', sa.JSON(), nullable=False),
    sa.Column('drafting_allowed_at_freeze', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_draft_input_snapshots_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_affiliate_program_id'], ['affiliate_programs.id'], name=op.f('fk_draft_input_snapshots_primary_affiliate_program_id_affiliate_programs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_draft_input_snapshots')),
    sa.UniqueConstraint('article_id', 'content_hash', name='uq_draft_input_snapshots_article_id')
    )
    with op.batch_alter_table('draft_input_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_draft_input_snapshots_article_frozen_id', ['article_id', 'frozen_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_input_snapshots_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_input_snapshots_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_input_snapshots_primary_affiliate_program_id'), ['primary_affiliate_program_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_input_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_input_snapshots_primary_affiliate_program_id'))
        batch_op.drop_index(batch_op.f('ix_draft_input_snapshots_content_hash'))
        batch_op.drop_index(batch_op.f('ix_draft_input_snapshots_article_id'))
        batch_op.drop_index('ix_draft_input_snapshots_article_frozen_id')

    op.drop_table('draft_input_snapshots')
    # ### end Alembic commands ###
