"""add keyword category, opportunity_score and article published_url

Revision ID: 5be5b19f3007
Revises: 1892d6df0222
Create Date: 2026-08-27 15:33:07.650908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be5b19f3007'
down_revision: Union[str, Sequence[str], None] = '1892d6df0222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_url', sa.String(length=1024), nullable=True))

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('opportunity_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_column('opportunity_score')
        batch_op.drop_column('category')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('published_url')

    # ### end Alembic commands ###
