"""add article_draft_promotions

Revision ID: 71fe1f7da534
Revises: 3e86dc460cd9
Create Date: 2026-09-04 09:27:19.640659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71fe1f7da534'
down_revision: Union[str, Sequence[str], None] = '3e86dc460cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_draft_promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=False),
    sa.Column('source_prompt_input_hash', sa.String(length=64), nullable=False),
    sa.Column('source_rendered_prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('meta_description', sa.String(length=400), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('meta_hash', sa.String(length=64), nullable=False),
    sa.Column('candidate_content_hash', sa.String(length=64), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=False),
    sa.Column('human_review_notes', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_draft_promotions_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_run_id'], ['draft_generation_runs.id'], name=op.f('fk_article_draft_promotions_source_run_id_draft_generation_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_draft_promotions')),
    sa.UniqueConstraint('idempotency_key', name='uq_article_draft_promotions_idempotency_key')
    )
    with op.batch_alter_table('article_draft_promotions', schema=None) as batch_op:
        batch_op.create_index('ix_article_draft_promotions_article_created_id', ['article_id', 'created_at', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_draft_promotions_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_draft_promotions_candidate_content_hash'), ['candidate_content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_draft_promotions_source_run_id'), ['source_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_draft_promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_draft_promotions_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_article_draft_promotions_candidate_content_hash'))
        batch_op.drop_index(batch_op.f('ix_article_draft_promotions_article_id'))
        batch_op.drop_index('ix_article_draft_promotions_article_created_id')

    op.drop_table('article_draft_promotions')
    # ### end Alembic commands ###
