"""add growth action history

Revision ID: 74bfaf6c9c9f
Revises: 2cfa0ccb2059
Create Date: 2026-09-29 18:31:28.685820

C9 Batch 2: Growth Action の候補の版・人のレビュー・出来事の表を 3 つ足すだけ。既存の表
(ChangeRequest・mobile approval・Threads の提案) は変えない。downgrade は 3 つの表を落とす
(この表の中の履歴だけが消える。ほかの表のデータには触れない)。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74bfaf6c9c9f'
down_revision: Union[str, Sequence[str], None] = '2cfa0ccb2059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_action_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_key', sa.String(length=255), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('candidate_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('evidence_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('identity_schema', sa.String(length=48), nullable=False),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('variant', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('availability_reasons_json', sa.JSON(), nullable=True),
    sa.Column('evidence_state', sa.String(length=24), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('observed', 'active', 'pending_review', 'approved', 'rejected', 'superseded', 'converted', 'dismissed')", name=op.f('ck_growth_action_candidates_growth_action_status')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_growth_action_candidates_growth_action_revision')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_growth_action_candidates_article_id_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_growth_action_candidates_keyword_id_keywords'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['growth_action_candidates.id'], name=op.f('fk_growth_action_candidates_superseded_by_id_growth_action_candidates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_action_candidates')),
    sa.UniqueConstraint('candidate_fingerprint', name='uq_growth_action_candidates_fingerprint'),
    sa.UniqueConstraint('opportunity_key', 'revision', name='uq_growth_action_candidates_opportunity_revision')
    )
    with op.batch_alter_table('growth_action_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_growth_action_candidates_opportunity', ['opportunity_key'], unique=False)
        batch_op.create_index('ix_growth_action_candidates_status', ['status'], unique=False)

    op.create_table('growth_action_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('review_schema', sa.String(length=48), nullable=False),
    sa.Column('opportunity_key', sa.String(length=255), nullable=False),
    sa.Column('candidate_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('evidence_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'stale')", name=op.f('ck_growth_action_reviews_growth_action_review_status')),
    sa.ForeignKeyConstraint(['candidate_id'], ['growth_action_candidates.id'], name=op.f('fk_growth_action_reviews_candidate_id_growth_action_candidates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_action_reviews')),
    sa.UniqueConstraint('candidate_id', name='uq_growth_action_reviews_candidate')
    )
    with op.batch_alter_table('growth_action_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_growth_action_reviews_status', ['status'], unique=False)

    op.create_table('growth_action_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("event_type IN ('observed', 'availability_changed', 'superseded', 'not_observed', 'review_requested', 'approved', 'rejected', 'review_stale', 'dismissed', 'conversion_planned')", name=op.f('ck_growth_action_events_growth_action_event_type')),
    sa.ForeignKeyConstraint(['candidate_id'], ['growth_action_candidates.id'], name=op.f('fk_growth_action_events_candidate_id_growth_action_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['growth_action_reviews.id'], name=op.f('fk_growth_action_events_review_id_growth_action_reviews'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_action_events'))
    )
    with op.batch_alter_table('growth_action_events', schema=None) as batch_op:
        batch_op.create_index('ix_growth_action_events_candidate', ['candidate_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('growth_action_events', schema=None) as batch_op:
        batch_op.drop_index('ix_growth_action_events_candidate')

    op.drop_table('growth_action_events')
    with op.batch_alter_table('growth_action_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_growth_action_reviews_status')

    op.drop_table('growth_action_reviews')
    with op.batch_alter_table('growth_action_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_growth_action_candidates_status')
        batch_op.drop_index('ix_growth_action_candidates_opportunity')

    op.drop_table('growth_action_candidates')
    # ### end Alembic commands ###
