"""add growth action conversions

Revision ID: 74dbecaa4bb2
Revises: 74bfaf6c9c9f
Create Date: 2026-09-29 20:46:20.959962

C9 Batch 3: 承認した Growth Action を既存の流れの手元の依頼へ渡した記録の表を 1 つ足し、
出来事の種類に conversion_executed / conversion_refused / conversion_failed を足す。既存の行・
ほかの表は変えない。downgrade は、新しい種類の出来事か変換の記録が 1 行でもあれば止まる
(消して戻すと記録が失われるため)。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

EVENTS = "growth_action_events"
CHECK_NAME = "ck_growth_action_events_growth_action_event_type"
V1 = ("observed", "availability_changed", "superseded", "not_observed", "review_requested",
      "approved", "rejected", "review_stale", "dismissed", "conversion_planned")
V2 = V1 + ("conversion_executed", "conversion_refused", "conversion_failed")


def _check(values) -> str:
    return "event_type IN (" + ", ".join(f"'{v}'" for v in values) + ")"


# revision identifiers, used by Alembic.
revision: str = '74dbecaa4bb2'
down_revision: Union[str, Sequence[str], None] = '74bfaf6c9c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_action_conversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=48), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('target_workflow', sa.String(length=64), nullable=False),
    sa.Column('candidate_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('downstream_type', sa.String(length=48), nullable=False),
    sa.Column('downstream_ids_json', sa.JSON(), nullable=False),
    sa.Column('local_writes_json', sa.JSON(), nullable=True),
    sa.Column('executed_by', sa.String(length=64), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('created', 'linked_existing')", name=op.f('ck_growth_action_conversions_growth_action_conversion_status')),
    sa.ForeignKeyConstraint(['candidate_id'], ['growth_action_candidates.id'], name=op.f('fk_growth_action_conversions_candidate_id_growth_action_candidates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['growth_action_reviews.id'], name=op.f('fk_growth_action_conversions_review_id_growth_action_reviews'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_action_conversions')),
    sa.UniqueConstraint('idempotency_key', name='uq_growth_action_conversions_idempotency')
    )
    with op.batch_alter_table('growth_action_conversions', schema=None) as batch_op:
        batch_op.create_index('ix_growth_action_conversions_candidate', ['candidate_id'], unique=False)

    # ### end Alembic commands ###
    with op.batch_alter_table(EVENTS, schema=None) as batch_op:
        batch_op.drop_constraint(op.f(CHECK_NAME), type_="check")
        batch_op.create_check_constraint("growth_action_event_type", _check(V2))


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    new_events = bind.execute(sa.text(
        f"SELECT COUNT(*) FROM {EVENTS} WHERE event_type NOT IN ("
        + ", ".join(f"'{v}'" for v in V1) + ")")).scalar()
    conversions = bind.execute(sa.text("SELECT COUNT(*) FROM growth_action_conversions")).scalar()
    if new_events or conversions:
        raise RuntimeError(
            f"refusing to downgrade: {conversions} conversion row(s) and {new_events} "
            "conversion event(s) would be lost")
    with op.batch_alter_table(EVENTS, schema=None) as batch_op:
        batch_op.drop_constraint(op.f(CHECK_NAME), type_="check")
        batch_op.create_check_constraint("growth_action_event_type", _check(V1))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('growth_action_conversions', schema=None) as batch_op:
        batch_op.drop_index('ix_growth_action_conversions_candidate')

    op.drop_table('growth_action_conversions')
    # ### end Alembic commands ###
