"""add affiliate commission import foundation

Revision ID: 7cb3df2e7348
Revises: 3d98dc94680c
Create Date: 2026-09-17 02:40:14.208959

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cb3df2e7348"
down_revision: str | Sequence[str] | None = "3d98dc94680c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "affiliate_commission_import_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("affiliate_program_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_date_from", sa.Date(), nullable=True),
        sa.Column("requested_date_to", sa.Date(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("response_count", sa.Integer(), nullable=True),
        sa.Column("inserted_count", sa.Integer(), nullable=True),
        sa.Column("updated_count", sa.Integer(), nullable=True),
        sa.Column("unchanged_count", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("response_snapshot", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["affiliate_program_id"],
            ["affiliate_programs.id"],
            name=op.f(
                "fk_affiliate_commission_import_runs_affiliate_program_id_affiliate_programs"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_commission_import_runs")),
    )
    with op.batch_alter_table("affiliate_commission_import_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_affiliate_commission_import_runs_affiliate_program_id"),
            ["affiliate_program_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_affiliate_commission_import_runs_provider"), ["provider"], unique=False
        )

    op.create_table(
        "affiliate_commission_facts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("affiliate_program_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("source_commission_id", sa.String(length=128), nullable=False),
        sa.Column("source_organization_id", sa.String(length=128), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("provider_status", sa.String(length=100), nullable=False),
        # model 側 app.models.types.ExactDecimal(38, 18) と同じ DB 契約を、app.* を
        # import せずに自己完結で表現する: SQLite は VARCHAR(41) (TEXT affinity --
        # 素の NUMERIC は float 経由で非可逆)、それ以外は NUMERIC(38, 18)。
        # 41 = precision(38) + 符号 + 小数点 + 1 (ExactDecimal.load_dialect_impl と同値)。
        sa.Column(
            "commission_amount",
            sa.Numeric(precision=38, scale=18).with_variant(sa.String(length=41), "sqlite"),
            nullable=True,
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payout_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payout_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payout_realized_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_import_run_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["affiliate_program_id"],
            ["affiliate_programs.id"],
            name=op.f("fk_affiliate_commission_facts_affiliate_program_id_affiliate_programs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_import_run_id"],
            ["affiliate_commission_import_runs.id"],
            name=op.f(
                "fk_affiliate_commission_facts_source_import_run_id_affiliate_commission_import_runs"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_commission_facts")),
        sa.UniqueConstraint(
            "provider",
            "source_commission_id",
            name="uq_affiliate_commission_facts_provider_source_id",
        ),
    )
    with op.batch_alter_table("affiliate_commission_facts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_affiliate_commission_facts_affiliate_program_id"),
            ["affiliate_program_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_affiliate_commission_facts_provider"), ["provider"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_affiliate_commission_facts_source_import_run_id"),
            ["source_import_run_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("affiliate_commission_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_affiliate_commission_facts_source_import_run_id"))
        batch_op.drop_index(batch_op.f("ix_affiliate_commission_facts_provider"))
        batch_op.drop_index(batch_op.f("ix_affiliate_commission_facts_affiliate_program_id"))

    op.drop_table("affiliate_commission_facts")
    with op.batch_alter_table("affiliate_commission_import_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_affiliate_commission_import_runs_provider"))
        batch_op.drop_index(batch_op.f("ix_affiliate_commission_import_runs_affiliate_program_id"))

    op.drop_table("affiliate_commission_import_runs")
    # ### end Alembic commands ###
