"""add affiliate link targets

Revision ID: 821856f0c58d
Revises: 0e94a7f929dd
Create Date: 2026-09-07 01:42:06.951289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821856f0c58d'
down_revision: Union[str, Sequence[str], None] = '0e94a7f929dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_link_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('affiliate_program_id', sa.Integer(), nullable=False),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('destination_host', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('link_identity_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_program_id'], ['affiliate_programs.id'], name=op.f('fk_affiliate_link_targets_affiliate_program_id_affiliate_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_affiliate_link_targets_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['affiliate_link_targets.id'], name=op.f('fk_affiliate_link_targets_superseded_by_id_affiliate_link_targets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affiliate_link_targets')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_affiliate_link_targets_idempotency_key'))
    )
    with op.batch_alter_table('affiliate_link_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_link_targets_affiliate_program_id'), ['affiliate_program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_link_targets_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_link_targets_destination_host'), ['destination_host'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_link_targets_link_identity_hash'), ['link_identity_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_link_targets_token'), ['token'], unique=True)
        batch_op.create_index('uq_affiliate_link_targets_active_article_program', ['article_id', 'affiliate_program_id'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_link_targets', schema=None) as batch_op:
        batch_op.drop_index('uq_affiliate_link_targets_active_article_program', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_affiliate_link_targets_token'))
        batch_op.drop_index(batch_op.f('ix_affiliate_link_targets_link_identity_hash'))
        batch_op.drop_index(batch_op.f('ix_affiliate_link_targets_destination_host'))
        batch_op.drop_index(batch_op.f('ix_affiliate_link_targets_article_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_link_targets_affiliate_program_id'))

    op.drop_table('affiliate_link_targets')
    # ### end Alembic commands ###
