"""add threads approval digest workflow

Revision ID: 949edb90023f
Revises: 3e397a01af66
Create Date: 2026-09-24 22:33:04.869650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949edb90023f'
down_revision: Union[str, Sequence[str], None] = '3e397a01af66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# 権威ある既存の記録があるときだけ埋める。無ければ NULL のまま残す
# (updated_at などから推測して「それらしい精度」を作らない)。
#
# 1) セッションの request_sent_at <- そのセッションの承認依頼メールが
#    outcome='sent' で記録されている場合の finished_at (送信が完了した時刻)。
# 2) 提案の approval_request_sent_at <- その提案のセッションのうち、実際に届いた
#    最新の request_sent_at。
# 3) 提案の approved_at <- 携帯承認が approved で synchronized になったセッションの
#    decided_at。これは決定をローカルへ受理した時刻で、T4.2 のコードが承認時に
#    書く値とまったく同じ意味を持つ (だから同等の記録として使える)。
BACKFILL_STATEMENTS = (
    """
    UPDATE mobile_approval_sessions
    SET request_sent_at = (
        SELECT d.finished_at FROM notification_deliveries d
        WHERE d.id = mobile_approval_sessions.notification_delivery_id
          AND d.outcome = 'sent'
    )
    WHERE request_sent_at IS NULL AND notification_delivery_id IS NOT NULL
    """,
    """
    UPDATE threads_post_proposals
    SET approval_request_sent_at = (
        SELECT MAX(s.request_sent_at) FROM mobile_approval_sessions s
        WHERE s.subject_type = 'threads_post'
          AND s.subject_id = threads_post_proposals.id
          AND s.request_sent_at IS NOT NULL
    )
    WHERE approval_request_sent_at IS NULL
    """,
    """
    UPDATE threads_post_proposals
    SET approved_at = (
        SELECT s.decided_at FROM mobile_approval_sessions s
        WHERE s.subject_type = 'threads_post'
          AND s.subject_id = threads_post_proposals.id
          AND s.decision = 'approved'
          AND s.state = 'synchronized'
          AND s.decided_at IS NOT NULL
        ORDER BY s.decided_at DESC
        LIMIT 1
    )
    WHERE status = 'approved' AND approved_at IS NULL
    """,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads_approval_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_delivery_id', sa.Integer(), nullable=True),
    sa.Column('selected_json', sa.JSON(), nullable=False),
    sa.Column('suppressed_json', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("outcome IN ('sent', 'failed')", name=op.f('ck_threads_approval_digests_threads_approval_digests_outcome')),
    sa.ForeignKeyConstraint(['notification_delivery_id'], ['notification_deliveries.id'], name=op.f('fk_threads_approval_digests_notification_delivery_id_notification_deliveries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_approval_digests'))
    )
    with op.batch_alter_table('threads_approval_digests', schema=None) as batch_op:
        batch_op.create_index('ix_threads_approval_digests_sent_at', ['sent_at'], unique=False)

    op.create_table('threads_queue_control_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action IN ('hold', 'release', 'prefer_next', 'clear_preference', 'set_timing')", name=op.f('ck_threads_queue_control_events_threads_queue_control_events_action')),
    sa.ForeignKeyConstraint(['proposal_id'], ['threads_post_proposals.id'], name=op.f('fk_threads_queue_control_events_proposal_id_threads_post_proposals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_queue_control_events'))
    )
    with op.batch_alter_table('threads_queue_control_events', schema=None) as batch_op:
        batch_op.create_index('ix_threads_queue_control_events_proposal', ['proposal_id', 'created_at'], unique=False)

    with op.batch_alter_table('mobile_approval_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approval_digest_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mobile_approval_sessions_approval_digest_id'), ['approval_digest_id'], unique=False)

    with op.batch_alter_table('operations_locks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_token', sa.String(length=64), nullable=True))

    with op.batch_alter_table('threads_post_proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approval_request_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('not_before', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('held_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('hold_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###

    # -- backfill (T4.2) ---------------------------------------------------------
    for statement in BACKFILL_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads_post_proposals', schema=None) as batch_op:
        batch_op.drop_column('preferred_at')
        batch_op.drop_column('hold_reason')
        batch_op.drop_column('held_at')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('not_before')
        batch_op.drop_column('approval_request_sent_at')
        batch_op.drop_column('approved_at')

    with op.batch_alter_table('operations_locks', schema=None) as batch_op:
        batch_op.drop_column('owner_token')

    with op.batch_alter_table('mobile_approval_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mobile_approval_sessions_approval_digest_id'))
        batch_op.drop_column('approval_digest_id')
        batch_op.drop_column('request_sent_at')

    with op.batch_alter_table('threads_queue_control_events', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_queue_control_events_proposal')

    op.drop_table('threads_queue_control_events')
    with op.batch_alter_table('threads_approval_digests', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_approval_digests_sent_at')

    op.drop_table('threads_approval_digests')
    # ### end Alembic commands ###
