"""add ga4 import tables

Revision ID: 976de9865f45
Revises: 9bad0f88dd67
Create Date: 2026-09-22 22:50:46.746282



C5.2:

- ``ga4_import_runs``: GA4 Data API 取り込みの auditable な実行記録 (append-only、
  prepared -> running -> succeeded|failed)。retry は新しい run を append する。
  ``property_timezone`` を凍結する -- GA4 の日付は property のタイムゾーン暦日で
  あり、UTC / JST から変換なしに導出できないため。
- ``ga4_page_daily``: (property, date, page_path, channel_scope) が一意な日次指標。
  同じ期間の再取り込みは UPSERT で上書きされ、行は重複しない。
- ``channel_scope`` は ``all`` / ``organic_search`` の 2 値 (CHECK 制約)。全
  トラフィックをオーガニックと呼ばないために **別の行** として保持し、按分も推定も
  しない。
- 指標は GA4 が返した値をそのまま保存する (CHECK で非負のみ強制)。CTR や
  engagement rate をこちら側で再計算しない。
- backfill はしない。GA4 計測が始まるまでこの 2 表は空のままで、既存の
  Search Console 取り込みには一切影響しない。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976de9865f45'
down_revision: Union[str, Sequence[str], None] = '9bad0f88dd67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ga4_import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('property_timezone', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('import_identity_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('page_rows_received', sa.Integer(), nullable=True),
    sa.Column('page_rows_upserted', sa.Integer(), nullable=True),
    sa.Column('data_through_date', sa.Date(), nullable=True),
    sa.Column('response_snapshot', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ga4_import_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_ga4_import_runs_idempotency_key')
    )
    with op.batch_alter_table('ga4_import_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ga4_import_runs_import_identity_hash'), ['import_identity_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ga4_import_runs_property_id'), ['property_id'], unique=False)

    op.create_table('ga4_page_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.String(length=64), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('page_path', sa.String(length=2048), nullable=False),
    sa.Column('channel_scope', sa.String(length=32), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('engaged_sessions', sa.Integer(), nullable=False),
    sa.Column('screen_page_views', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('average_engagement_time_seconds', sa.Float(), nullable=False),
    sa.Column('source_import_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("channel_scope IN ('all', 'organic_search')", name=op.f('ck_ga4_page_daily_ga4_page_daily_channel_scope')),
    sa.CheckConstraint('sessions >= 0 AND active_users >= 0 AND new_users >= 0 AND engaged_sessions >= 0 AND screen_page_views >= 0', name=op.f('ck_ga4_page_daily_ga4_page_daily_non_negative')),
    sa.ForeignKeyConstraint(['source_import_run_id'], ['ga4_import_runs.id'], name=op.f('fk_ga4_page_daily_source_import_run_id_ga4_import_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ga4_page_daily')),
    sa.UniqueConstraint('property_id', 'metric_date', 'page_path', 'channel_scope', name='uq_ga4_page_daily_identity')
    )
    with op.batch_alter_table('ga4_page_daily', schema=None) as batch_op:
        batch_op.create_index('ix_ga4_page_daily_property_date', ['property_id', 'metric_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ga4_page_daily_source_import_run_id'), ['source_import_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ga4_page_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ga4_page_daily_source_import_run_id'))
        batch_op.drop_index('ix_ga4_page_daily_property_date')

    op.drop_table('ga4_page_daily')
    with op.batch_alter_table('ga4_import_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ga4_import_runs_property_id'))
        batch_op.drop_index(batch_op.f('ix_ga4_import_runs_import_identity_hash'))

    op.drop_table('ga4_import_runs')
    # ### end Alembic commands ###
