"""add wordpress_content_update_reconciliations

Revision ID: 9bad0f88dd67
Revises: 27655047edee
Create Date: 2026-09-22 21:54:42.451898



C4.9:

- ``wordpress_content_update_reconciliations``: ``outcome_unknown`` で終わった
  content-update run を、後から live な観測だけで照合した結果 (append-only)。
  run 行の status は書き換えない -- 「実行時に何を観測したか」という監査事実を
  保持したまま、「後から人間が照合して何を確認したか」を独立した行として残す。
- ``verdict`` は ``reconciled_succeeded`` / ``unresolved`` の 2 値のみ
  (CHECK 制約)。``reconciled_succeeded`` を持つ run だけが blocking から外れる。
- ``wordpress_content_update_run_id`` は UNIQUE -- 1 run につき verdict は 1 つ。
  2 回目の reconcile は既存行を返す no-op になり、重複記録も追加の GET も無い。
- FK は article / run とも RESTRICT。照合結果が参照している限り削除できない。
- backfill はしない。既存の run は全て「reconciliation 無し」= 従来どおりの
  blocking 判定のまま動く。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bad0f88dd67'
down_revision: Union[str, Sequence[str], None] = '27655047edee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordpress_content_update_reconciliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wordpress_content_update_run_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('wordpress_post_id', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('unresolved_reason_code', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('observed_wordpress_status', sa.String(length=20), nullable=True),
    sa.Column('observed_wordpress_raw_content_hash', sa.String(length=64), nullable=True),
    sa.Column('observed_modified_gmt_raw', sa.String(length=64), nullable=True),
    sa.Column('pre_update_wordpress_raw_content_hash', sa.String(length=64), nullable=False),
    sa.Column('request_content_hash', sa.String(length=64), nullable=False),
    sa.Column('comparison_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("verdict IN ('reconciled_succeeded', 'unresolved')", name=op.f('ck_wordpress_content_update_reconciliations_wp_content_update_reconciliation_verdict')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_wordpress_content_update_reconciliations_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wordpress_content_update_run_id'], ['wordpress_content_update_runs.id'], name=op.f('fk_wordpress_content_update_reconciliations_wordpress_content_update_run_id_wordpress_content_update_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wordpress_content_update_reconciliations')),
    sa.UniqueConstraint('idempotency_key', name='uq_wp_content_update_reconciliations_idempotency_key'),
    sa.UniqueConstraint('wordpress_content_update_run_id', name='uq_wp_content_update_reconciliations_run')
    )
    with op.batch_alter_table('wordpress_content_update_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wordpress_content_update_reconciliations_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wordpress_content_update_reconciliations_wordpress_content_update_run_id'), ['wordpress_content_update_run_id'], unique=False)
        batch_op.create_index('ix_wp_content_update_reconciliations_article_created_id', ['article_id', 'created_at', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordpress_content_update_reconciliations', schema=None) as batch_op:
        batch_op.drop_index('ix_wp_content_update_reconciliations_article_created_id')
        batch_op.drop_index(batch_op.f('ix_wordpress_content_update_reconciliations_wordpress_content_update_run_id'))
        batch_op.drop_index(batch_op.f('ix_wordpress_content_update_reconciliations_article_id'))

    op.drop_table('wordpress_content_update_reconciliations')
    # ### end Alembic commands ###
