"""add notification delivery history

Revision ID: a2950e9577cd
Revises: 39c2fa18fb6a
Create Date: 2026-09-23 23:44:30.592625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2950e9577cd'
down_revision: Union[str, Sequence[str], None] = '39c2fa18fb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operations_run_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('recipient_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('recipient_hint', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("channel IN ('email')", name=op.f('ck_notification_deliveries_notification_deliveries_channel')),
    sa.CheckConstraint("outcome IN ('sent', 'failed', 'skipped', 'duplicate')", name=op.f('ck_notification_deliveries_notification_deliveries_outcome')),
    sa.ForeignKeyConstraint(['alert_id'], ['operations_alerts.id'], name=op.f('fk_notification_deliveries_alert_id_operations_alerts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operations_run_id'], ['operations_runs.id'], name=op.f('fk_notification_deliveries_operations_run_id_operations_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_deliveries_dedupe_key')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_notification_deliveries_run', ['operations_run_id'], unique=False)
        batch_op.create_index('ix_notification_deliveries_type', ['notification_type', 'outcome'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_deliveries_type')
        batch_op.drop_index('ix_notification_deliveries_run')

    op.drop_table('notification_deliveries')
    # ### end Alembic commands ###
