"""add note pieces and manual metric entries

Revision ID: a4a74a5bcb8b
Revises: c1d0e233e180
Create Date: 2026-09-30 09:18:12.210297

N2 / N3: note の 1 本ずつの記録 (``note_pieces``) と、手で写した数の記録
(``manual_metric_entries``) の表を足すだけ。既存の表は変えない。downgrade は、どちらかの表に
1 行でもあれば止まる (記録が失われるため)。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a74a5bcb8b'
down_revision: Union[str, Sequence[str], None] = 'c1d0e233e180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_metric_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_key', sa.String(length=64), nullable=False),
    sa.Column('subject_kind', sa.String(length=16), nullable=False),
    sa.Column('subject_ref', sa.String(length=200), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('source_description', sa.String(length=300), nullable=False),
    sa.Column('entered_by', sa.String(length=64), nullable=False),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('supersedes_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("provenance IN ('manual_entry')", name=op.f('ck_manual_metric_entries_manual_metric_provenance')),
    sa.CheckConstraint("subject_kind IN ('note_piece', 'channel', 'product', 'pilot')", name=op.f('ck_manual_metric_entries_manual_metric_subject')),
    sa.CheckConstraint('period_end IS NULL OR period_start IS NULL OR period_end >= period_start', name=op.f('ck_manual_metric_entries_manual_metric_period')),
    sa.CheckConstraint('value >= 0', name=op.f('ck_manual_metric_entries_manual_metric_value')),
    sa.ForeignKeyConstraint(['supersedes_entry_id'], ['manual_metric_entries.id'], name=op.f('fk_manual_metric_entries_supersedes_entry_id_manual_metric_entries'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_metric_entries')),
    sa.UniqueConstraint('entry_key', name='uq_manual_metric_entries_entry_key')
    )
    with op.batch_alter_table('manual_metric_entries', schema=None) as batch_op:
        batch_op.create_index('ix_manual_metric_entries_subject', ['subject_kind', 'subject_ref', 'metric'], unique=False)

    op.create_table('note_pieces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('access_mode', sa.String(length=8), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('source_event_ids_json', sa.JSON(), nullable=True),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_hash', sa.String(length=64), nullable=True),
    sa.Column('approval_json', sa.JSON(), nullable=True),
    sa.Column('published_url', sa.String(length=500), nullable=True),
    sa.Column('published_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('draft_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("access_mode IN ('free', 'paid')", name=op.f('ck_note_pieces_note_piece_access')),
    sa.CheckConstraint("status != 'published' OR published_url IS NOT NULL", name=op.f('ck_note_pieces_note_piece_published_has_url')),
    sa.CheckConstraint("status IN ('draft', 'review_ready', 'approved', 'published', 'rejected')", name=op.f('ck_note_pieces_note_piece_status')),
    sa.CheckConstraint("status NOT IN ('approved', 'published') OR approved_hash IS NOT NULL", name=op.f('ck_note_pieces_note_piece_approved_has_hash')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_pieces')),
    sa.UniqueConstraint('draft_id', name='uq_note_pieces_draft_id'),
    sa.UniqueConstraint('published_url', name='uq_note_pieces_published_url')
    )
    with op.batch_alter_table('note_pieces', schema=None) as batch_op:
        batch_op.create_index('ix_note_pieces_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    for table in ("manual_metric_entries", "note_pieces"):
        rows = bind.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar()
        if rows:
            raise RuntimeError(f"refusing to downgrade: {rows} row(s) in {table} would be lost")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_pieces', schema=None) as batch_op:
        batch_op.drop_index('ix_note_pieces_status')

    op.drop_table('note_pieces')
    with op.batch_alter_table('manual_metric_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_manual_metric_entries_subject')

    op.drop_table('manual_metric_entries')
    # ### end Alembic commands ###
