"""add affiliate_program match_terms and currency

Revision ID: abfa2f774ff4
Revises: 1689a1b083a8
Create Date: 2026-08-28 10:00:13.643784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfa2f774ff4'
down_revision: Union[str, Sequence[str], None] = '1689a1b083a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('match_terms', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_programs', schema=None) as batch_op:
        batch_op.drop_column('match_terms')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
