"""add threads digest window override audit

Revision ID: b11082319d9d
Revises: 949edb90023f
Create Date: 2026-09-24 23:29:33.927109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11082319d9d'
down_revision: Union[str, Sequence[str], None] = '949edb90023f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads_approval_digests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_override_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('window_override_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads_approval_digests', schema=None) as batch_op:
        batch_op.drop_column('window_override_at')
        batch_op.drop_column('window_override_reason')

    # ### end Alembic commands ###
