"""add threads post proposals

Revision ID: b1c9ed9e3f71
Revises: d68b17b583bb
Create Date: 2026-09-24 02:27:34.020604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c9ed9e3f71'
down_revision: Union[str, Sequence[str], None] = 'd68b17b583bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads_post_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_article_id', sa.Integer(), nullable=False),
    sa.Column('source_article_body_hash', sa.String(length=64), nullable=False),
    sa.Column('angle', sa.String(length=32), nullable=False),
    sa.Column('link_mode', sa.String(length=16), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('destination_url', sa.String(length=1024), nullable=True),
    sa.Column('content_seed', sa.String(length=64), nullable=False),
    sa.Column('proposal_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('generator_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('change_request_approval_id', sa.Integer(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("link_mode IN ('none', 'article')", name=op.f('ck_threads_post_proposals_threads_proposals_link_mode')),
    sa.CheckConstraint('character_count > 0', name=op.f('ck_threads_post_proposals_threads_proposals_length')),
    sa.ForeignKeyConstraint(['change_request_approval_id'], ['change_request_approvals.id'], name=op.f('fk_threads_post_proposals_change_request_approval_id_change_request_approvals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_article_id'], ['articles.id'], name=op.f('fk_threads_post_proposals_source_article_id_articles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_threads_post_proposals')),
    sa.UniqueConstraint('proposal_hash', name='uq_threads_post_proposals_hash')
    )
    with op.batch_alter_table('threads_post_proposals', schema=None) as batch_op:
        batch_op.create_index('ix_threads_post_proposals_article', ['source_article_id'], unique=False)
        batch_op.create_index('ix_threads_post_proposals_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads_post_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_threads_post_proposals_status')
        batch_op.drop_index('ix_threads_post_proposals_article')

    op.drop_table('threads_post_proposals')
    # ### end Alembic commands ###
