"""add article_facts

Revision ID: ba2e8486248e
Revises: abfa2f774ff4
Create Date: 2026-08-28 14:57:11.891949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2e8486248e'
down_revision: Union[str, Sequence[str], None] = 'abfa2f774ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('subject_ref', sa.String(length=200), nullable=False),
    sa.Column('affiliate_program_id', sa.Integer(), nullable=True),
    sa.Column('fact_key', sa.String(length=64), nullable=False),
    sa.Column('fact_value', sa.JSON(), nullable=True),
    sa.Column('value_status', sa.String(length=20), nullable=False),
    sa.Column('unknown_reason', sa.String(length=500), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_program_id'], ['affiliate_programs.id'], name=op.f('fk_article_facts_affiliate_program_id_affiliate_programs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_facts_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_article_facts_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_facts'))
    )
    with op.batch_alter_table('article_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_facts_affiliate_program_id'), ['affiliate_program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_facts_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_article_facts_article_subject_key', ['article_id', 'subject_ref', 'fact_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_facts_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_facts_source_id'))
        batch_op.drop_index('ix_article_facts_article_subject_key')
        batch_op.drop_index(batch_op.f('ix_article_facts_article_id'))
        batch_op.drop_index(batch_op.f('ix_article_facts_affiliate_program_id'))

    op.drop_table('article_facts')
    # ### end Alembic commands ###
