"""add content discovery and nightly analysis runs

Revision ID: c1d0e233e180
Revises: 4fe83827d695
Create Date: 2026-09-30 01:56:27.143420

C10-2: 夜の分析の実行の記録 (``nightly_analysis_runs``) と発見した語の候補
(``content_discovery_candidates``) の表を足すだけ。既存の表は変えない。downgrade は、どちらかの表に
1 行でもあれば止まる (記録が失われるため)。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d0e233e180'
down_revision: Union[str, Sequence[str], None] = '4fe83827d695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nightly_analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_key', sa.String(length=64), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('universe_count', sa.Integer(), nullable=False),
    sa.Column('eligible_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('deferred_count', sa.Integer(), nullable=False),
    sa.Column('refresh_required_count', sa.Integer(), nullable=False),
    sa.Column('next_article_count', sa.Integer(), nullable=False),
    sa.Column('counts_json', sa.JSON(), nullable=True),
    sa.Column('refresh_plan_json', sa.JSON(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'succeeded', 'failed')", name=op.f('ck_nightly_analysis_runs_nightly_analysis_status')),
    sa.CheckConstraint('attempt_count >= 1', name=op.f('ck_nightly_analysis_runs_nightly_analysis_attempts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nightly_analysis_runs')),
    sa.UniqueConstraint('run_key', name='uq_nightly_analysis_runs_run_key')
    )
    op.create_table('content_discovery_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phrase_key', sa.String(length=255), nullable=False),
    sa.Column('phrase', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duplicate_state', sa.String(length=32), nullable=False),
    sa.Column('duplicate_ref_json', sa.JSON(), nullable=True),
    sa.Column('cluster_key', sa.String(length=16), nullable=True),
    sa.Column('cluster_basis', sa.String(length=32), nullable=True),
    sa.Column('sources_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('refresh_needs_json', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('first_run_id', sa.Integer(), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('tracked', 'suppressed', 'promoted', 'dismissed')", name=op.f('ck_content_discovery_candidates_content_discovery_status')),
    sa.CheckConstraint('seen_count >= 1', name=op.f('ck_content_discovery_candidates_content_discovery_seen')),
    sa.ForeignKeyConstraint(['first_run_id'], ['nightly_analysis_runs.id'], name=op.f('fk_content_discovery_candidates_first_run_id_nightly_analysis_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_content_discovery_candidates_keyword_id_keywords'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_run_id'], ['nightly_analysis_runs.id'], name=op.f('fk_content_discovery_candidates_last_run_id_nightly_analysis_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_discovery_candidates')),
    sa.UniqueConstraint('phrase_key', name='uq_content_discovery_candidates_phrase_key')
    )
    with op.batch_alter_table('content_discovery_candidates', schema=None) as batch_op:
        batch_op.create_index('ix_content_discovery_candidates_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    for table in ("content_discovery_candidates", "nightly_analysis_runs"):
        rows = bind.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar()
        if rows:
            raise RuntimeError(f"refusing to downgrade: {rows} row(s) in {table} would be lost")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_discovery_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_content_discovery_candidates_status')

    op.drop_table('content_discovery_candidates')
    op.drop_table('nightly_analysis_runs')
    # ### end Alembic commands ###
