"""add seo improvement candidate tables

Revision ID: c26d25db8dc8
Revises: 976de9865f45
Create Date: 2026-09-22 23:49:20.912305



C6:

- ``seo_improvement_runs``: SEO 改善候補の評価 1 回分 (append-only)。既存 run は
  書き換えない。``policy_version`` / ``window`` / ``gsc_data_through`` /
  ``ga4_data_through`` / ``index_observed_at`` を凍結し、「なぜその日はその判断に
  なったか」を後から再現できるようにする。
- ``seo_improvement_candidates``: 1 件の候補のスナップショット。
  ``(run_id, dedupe_key)`` の UNIQUE が同一 run 内の重複を DB 層で防ぐ。
  ``dedupe_key`` は run をまたいで安定なので、「同じ候補が何日続いているか」を
  追える。
- 優先度は ``high/medium/low`` の 3 値のみで、明示規則からしか決まらない。
  不透明な合成スコアは持たない。
- FK は article / run とも RESTRICT。候補が参照している限り削除できない。
- 記事本文・credential は保存しない。この 2 表は記事を一切変更しない。
- backfill はしない。評価を実行するまで空のままで、既存の取り込みには影響しない。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26d25db8dc8'
down_revision: Union[str, Sequence[str], None] = '976de9865f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_improvement_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('gsc_data_through', sa.Date(), nullable=True),
    sa.Column('ga4_data_through', sa.Date(), nullable=True),
    sa.Column('index_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_article_count', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_improvement_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_seo_improvement_runs_idempotency_key')
    )
    with op.batch_alter_table('seo_improvement_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_improvement_runs_policy_version'), ['policy_version'], unique=False)

    op.create_table('seo_improvement_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seo_improvement_run_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('candidate_type', sa.String(length=64), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('evidence_strength', sa.String(length=32), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_seo_improvement_candidates_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seo_improvement_run_id'], ['seo_improvement_runs.id'], name=op.f('fk_seo_improvement_candidates_seo_improvement_run_id_seo_improvement_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_improvement_candidates')),
    sa.UniqueConstraint('seo_improvement_run_id', 'dedupe_key', name='uq_seo_improvement_candidates_identity')
    )
    with op.batch_alter_table('seo_improvement_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seo_improvement_candidates_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_seo_improvement_candidates_article_run', ['article_id', 'seo_improvement_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seo_improvement_candidates_seo_improvement_run_id'), ['seo_improvement_run_id'], unique=False)
        batch_op.create_index('ix_seo_improvement_candidates_type', ['candidate_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seo_improvement_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_seo_improvement_candidates_type')
        batch_op.drop_index(batch_op.f('ix_seo_improvement_candidates_seo_improvement_run_id'))
        batch_op.drop_index('ix_seo_improvement_candidates_article_run')
        batch_op.drop_index(batch_op.f('ix_seo_improvement_candidates_article_id'))

    op.drop_table('seo_improvement_candidates')
    with op.batch_alter_table('seo_improvement_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seo_improvement_runs_policy_version'))

    op.drop_table('seo_improvement_runs')
    # ### end Alembic commands ###
