"""add revenue optimization tables

Revision ID: c28f868e971a
Revises: c26d25db8dc8
Create Date: 2026-09-23 00:18:49.666122



C7:

- ``revenue_optimization_runs``: 収益最適化の評価 1 回分 (append-only)。
  ``policy_version`` / window / ``trusted_measurement_start_at`` / 各データの
  data-through / raw・excluded・clean のクリック数を凍結する。とくに
  ``trusted_measurement_start_at`` が無いと、「どの時点以降のクリックを読者行動と
  みなしたか」が後から分からず、判断を再現できない。
- ``revenue_optimization_candidates``: 1 件の候補のスナップショット。
  ``(run_id, dedupe_key)`` の UNIQUE が同一 run 内の重複を DB 層で防ぐ。
- ``article_id`` / ``affiliate_program_id`` はどちらも nullable。記事単位・
  プログラム単位・計測全体の候補を同じ表で扱うため。FK はいずれも RESTRICT。
- 優先度は high/medium/low の 3 値で、明示規則からしか決まらない。合成スコアは無い。
- ``evidence_basis`` で structural / behavioral / program_level / data_quality を
  区別する -- 構造的な事実と読者の行動を混同させないための列。
- backfill はしない。評価を実行するまで空のままで、既存の取り込み・記事・
  WordPress には一切影響しない。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28f868e971a'
down_revision: Union[str, Sequence[str], None] = 'c26d25db8dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_optimization_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('trusted_measurement_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ga4_data_through', sa.Date(), nullable=True),
    sa.Column('affiliate_click_data_through', sa.Date(), nullable=True),
    sa.Column('commission_data_through', sa.Date(), nullable=True),
    sa.Column('raw_clicks', sa.Integer(), nullable=False),
    sa.Column('excluded_clicks', sa.Integer(), nullable=False),
    sa.Column('clean_clicks', sa.Integer(), nullable=False),
    sa.Column('evaluated_article_count', sa.Integer(), nullable=False),
    sa.Column('monetized_article_count', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_optimization_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_revenue_optimization_runs_idempotency_key')
    )
    with op.batch_alter_table('revenue_optimization_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenue_optimization_runs_policy_version'), ['policy_version'], unique=False)

    op.create_table('revenue_optimization_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('revenue_optimization_run_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('affiliate_program_id', sa.Integer(), nullable=True),
    sa.Column('candidate_type', sa.String(length=64), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('evidence_basis', sa.String(length=32), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_program_id'], ['affiliate_programs.id'], name=op.f('fk_revenue_optimization_candidates_affiliate_program_id_affiliate_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_revenue_optimization_candidates_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revenue_optimization_run_id'], ['revenue_optimization_runs.id'], name=op.f('fk_revenue_optimization_candidates_revenue_optimization_run_id_revenue_optimization_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_optimization_candidates')),
    sa.UniqueConstraint('revenue_optimization_run_id', 'dedupe_key', name='uq_revenue_optimization_candidates_identity')
    )
    with op.batch_alter_table('revenue_optimization_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenue_optimization_candidates_affiliate_program_id'), ['affiliate_program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_optimization_candidates_article_id'), ['article_id'], unique=False)
        batch_op.create_index('ix_revenue_optimization_candidates_article_run', ['article_id', 'revenue_optimization_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_optimization_candidates_revenue_optimization_run_id'), ['revenue_optimization_run_id'], unique=False)
        batch_op.create_index('ix_revenue_optimization_candidates_type', ['candidate_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revenue_optimization_candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_revenue_optimization_candidates_type')
        batch_op.drop_index(batch_op.f('ix_revenue_optimization_candidates_revenue_optimization_run_id'))
        batch_op.drop_index('ix_revenue_optimization_candidates_article_run')
        batch_op.drop_index(batch_op.f('ix_revenue_optimization_candidates_article_id'))
        batch_op.drop_index(batch_op.f('ix_revenue_optimization_candidates_affiliate_program_id'))

    op.drop_table('revenue_optimization_candidates')
    with op.batch_alter_table('revenue_optimization_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_optimization_runs_policy_version'))

    op.drop_table('revenue_optimization_runs')
    # ### end Alembic commands ###
