"""add keyword_scores

Revision ID: ca2a50f798ec
Revises: 5be5b19f3007
Create Date: 2026-08-27 15:56:53.011050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2a50f798ec'
down_revision: Union[str, Sequence[str], None] = '5be5b19f3007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('search_demand', sa.Float(), nullable=False),
    sa.Column('commercial_intent', sa.Float(), nullable=False),
    sa.Column('affiliate_opportunity', sa.Float(), nullable=False),
    sa.Column('competition_ease', sa.Float(), nullable=False),
    sa.Column('trend', sa.Float(), nullable=False),
    sa.Column('originality', sa.Float(), nullable=False),
    sa.Column('site_relevance', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('score_version', sa.String(length=20), nullable=False),
    sa.Column('input_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('affiliate_opportunity BETWEEN 0 AND 100', name=op.f('ck_keyword_scores_affiliate_opportunity_range')),
    sa.CheckConstraint('commercial_intent BETWEEN 0 AND 100', name=op.f('ck_keyword_scores_commercial_intent_range')),
    sa.CheckConstraint('competition_ease BETWEEN 0 AND 100', name=op.f('ck_keyword_scores_competition_ease_range')),
    sa.CheckConstraint('originality BETWEEN 0 AND 100', name=op.f('ck_keyword_scores_originality_range')),
    sa.CheckConstraint('search_demand BETWEEN 0 AND 100', name=op.f('ck_keyword_scores_search_demand_range')),
    sa.CheckConstraint('site_relevance BETWEEN 0 AND 100', name=op.f('ck_keyword_scores_site_relevance_range')),
    sa.CheckConstraint('total_score BETWEEN 0 AND 100', name=op.f('ck_keyword_scores_total_score_range')),
    sa.CheckConstraint('trend BETWEEN 0 AND 100', name=op.f('ck_keyword_scores_trend_range')),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], name=op.f('fk_keyword_scores_keyword_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_scores'))
    )
    with op.batch_alter_table('keyword_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_scores_keyword_id'), ['keyword_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_scores_keyword_id'))

    op.drop_table('keyword_scores')
    # ### end Alembic commands ###
