"""add mobile approval sessions

Revision ID: d68b17b583bb
Revises: a2950e9577cd
Create Date: 2026-09-24 00:19:38.765604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68b17b583bb'
down_revision: Union[str, Sequence[str], None] = 'a2950e9577cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_approval_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_hash', sa.String(length=64), nullable=False),
    sa.Column('subject_version', sa.Integer(), nullable=False),
    sa.Column('relay_session_id', sa.String(length=64), nullable=False),
    sa.Column('capability_digest', sa.String(length=64), nullable=False),
    sa.Column('capability_binding', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('state_reason', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synchronized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_request_approval_id', sa.Integer(), nullable=True),
    sa.Column('notification_delivery_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("decision IS NULL OR decision IN ('approved', 'rejected')", name=op.f('ck_mobile_approval_sessions_mobile_approval_decision')),
    sa.CheckConstraint("subject_type IN ('change_request', 'threads_post')", name=op.f('ck_mobile_approval_sessions_mobile_approval_subject_type')),
    sa.ForeignKeyConstraint(['change_request_approval_id'], ['change_request_approvals.id'], name=op.f('fk_mobile_approval_sessions_change_request_approval_id_change_request_approvals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['notification_delivery_id'], ['notification_deliveries.id'], name=op.f('fk_mobile_approval_sessions_notification_delivery_id_notification_deliveries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mobile_approval_sessions')),
    sa.UniqueConstraint('capability_digest', name='uq_mobile_approval_capability'),
    sa.UniqueConstraint('relay_session_id', name='uq_mobile_approval_relay_session')
    )
    with op.batch_alter_table('mobile_approval_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_mobile_approval_state', ['state'], unique=False)
        batch_op.create_index('ix_mobile_approval_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('mobile_approval_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobile_approval_session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=True),
    sa.Column('to_state', sa.String(length=24), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mobile_approval_session_id'], ['mobile_approval_sessions.id'], name=op.f('fk_mobile_approval_events_mobile_approval_session_id_mobile_approval_sessions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mobile_approval_events'))
    )
    with op.batch_alter_table('mobile_approval_events', schema=None) as batch_op:
        batch_op.create_index('ix_mobile_approval_events_session', ['mobile_approval_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobile_approval_events', schema=None) as batch_op:
        batch_op.drop_index('ix_mobile_approval_events_session')

    op.drop_table('mobile_approval_events')
    with op.batch_alter_table('mobile_approval_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_mobile_approval_subject')
        batch_op.drop_index('ix_mobile_approval_state')

    op.drop_table('mobile_approval_sessions')
    # ### end Alembic commands ###
