"""add operations runs alerts and locks

Revision ID: e1b541ec6d33
Revises: c28f868e971a
Create Date: 2026-09-23 00:36:07.736095



C8:

- ``operations_runs`` / ``operations_step_runs``: 定期実行の append-only な記録。
  profile / policy_version / 運用タイムゾーンの effective_date / trigger /
  git revision / schema version を凍結し、「その日なぜそう動いたか」を後から
  再現できるようにする。step は source 側の run id と行数まで持つ。
- ``operations_alerts``: 運用アラート。``fingerprint`` が UNIQUE で、同じ問題が
  続く間は last_seen_at と occurrence_count を進めるだけ。毎日新しい通知を出さない
  ための土台であり、課題管理システムではない (状態は open/acknowledged/resolved の
  3 値のみ)。severity は CHECK 制約で info/warning/error に限定する。
- ``operations_locks``: 同時実行を防ぐ排他。これだけは append-only ではない
  (排他の性質上 1 行を取得・解放する)。所有者 run id と acquired_at/heartbeat_at を
  必ず持ち、プロセスが死んでも時間経過で回収できる -- 恒久デッドロックにしない。
- credential / tracking URL / /go/ token はいずれの表にも保存しない。
- backfill はしない。記事・WordPress・既存の取り込みには一切影響しない。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b541ec6d33'
down_revision: Union[str, Sequence[str], None] = 'c28f868e971a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations_locks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lock_name', sa.String(length=64), nullable=False),
    sa.Column('owner_run_id', sa.Integer(), nullable=True),
    sa.Column('owner_label', sa.String(length=128), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations_locks')),
    sa.UniqueConstraint('lock_name', name='uq_operations_locks_name')
    )
    op.create_table('operations_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('git_revision', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=64), nullable=True),
    sa.Column('step_total', sa.Integer(), nullable=False),
    sa.Column('step_succeeded', sa.Integer(), nullable=False),
    sa.Column('step_failed', sa.Integer(), nullable=False),
    sa.Column('step_skipped', sa.Integer(), nullable=False),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_operations_runs_idempotency_key')
    )
    with op.batch_alter_table('operations_runs', schema=None) as batch_op:
        batch_op.create_index('ix_operations_runs_profile_date', ['profile', 'effective_date'], unique=False)

    op.create_table('operations_step_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operations_run_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_run_id', sa.Integer(), nullable=True),
    sa.Column('rows_received', sa.Integer(), nullable=True),
    sa.Column('rows_changed', sa.Integer(), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['operations_run_id'], ['operations_runs.id'], name=op.f('fk_operations_step_runs_operations_run_id_operations_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations_step_runs'))
    )
    with op.batch_alter_table('operations_step_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_step_runs_operations_run_id'), ['operations_run_id'], unique=False)
        batch_op.create_index('ix_operations_step_runs_run_step', ['operations_run_id', 'step_name'], unique=False)

    op.create_table('operations_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('affiliate_program_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('operations_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'error')", name=op.f('ck_operations_alerts_operations_alerts_severity')),
    sa.ForeignKeyConstraint(['affiliate_program_id'], ['affiliate_programs.id'], name=op.f('fk_operations_alerts_affiliate_program_id_affiliate_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_operations_alerts_article_id_articles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operations_run_id'], ['operations_runs.id'], name=op.f('fk_operations_alerts_operations_run_id_operations_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations_alerts')),
    sa.UniqueConstraint('fingerprint', name='uq_operations_alerts_fingerprint')
    )
    with op.batch_alter_table('operations_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operations_alerts_affiliate_program_id'), ['affiliate_program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_alerts_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operations_alerts_operations_run_id'), ['operations_run_id'], unique=False)
        batch_op.create_index('ix_operations_alerts_type_severity', ['alert_type', 'severity'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_operations_alerts_type_severity')
        batch_op.drop_index(batch_op.f('ix_operations_alerts_operations_run_id'))
        batch_op.drop_index(batch_op.f('ix_operations_alerts_article_id'))
        batch_op.drop_index(batch_op.f('ix_operations_alerts_affiliate_program_id'))

    op.drop_table('operations_alerts')
    with op.batch_alter_table('operations_step_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_operations_step_runs_run_step')
        batch_op.drop_index(batch_op.f('ix_operations_step_runs_operations_run_id'))

    op.drop_table('operations_step_runs')
    with op.batch_alter_table('operations_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_operations_runs_profile_date')

    op.drop_table('operations_runs')
    op.drop_table('operations_locks')
    # ### end Alembic commands ###
