"""C2.3 の 135 候補と、その人手判定 (keep / merge / reject) の期待値。

expansion planner がこの判定を再現できることを検証するための固定データ (test 専用)。
``merge`` の対象は C2.3 で決めた吸収先。既存 article の keyword / 既存 slot / 候補のいずれか。
"""

from __future__ import annotations

# (cluster, keyword, decision, merge target or None)
CASES: tuple[tuple[str, str, str, str | None], ...] = (
    ("B", "タスク管理 ツール おすすめ", "keep", None),
    ("B", "タスク管理 ツール 比較", "merge", "タスク管理 ツール おすすめ"),
    ("B", "タスク管理 ツール 無料", "keep", None),
    ("B", "プロジェクト管理 ツール おすすめ", "keep", None),
    ("B", "プロジェクト管理 ツール 比較", "merge", "プロジェクト管理 ツール おすすめ"),
    ("B", "プロジェクト管理 ツール 無料", "keep", None),
    ("B", "ClickUp 使い方", "keep", None),
    ("B", "ClickUp 料金", "keep", None),
    ("B", "ClickUp 代替", "keep", None),
    ("B", "monday.com 料金", "keep", None),
    ("B", "monday.com 使い方", "keep", None),
    ("B", "monday.com 代替", "keep", None),
    ("B", "Todoist 使い方", "reject", None),
    ("B", "Todoist 料金", "keep", None),
    ("B", "業務効率化 ツール 中小企業", "merge", "業務効率化 ツール おすすめ"),
    ("B", "業務効率化 ツール 事例", "keep", None),
    ("B", "業務効率化 アイデア", "reject", None),
    ("B", "業務効率化 AI ツール", "merge", "AI 業務効率化"),
    ("B", "日程調整 ツール おすすめ", "keep", None),
    ("B", "スケジュール管理 ツール 比較", "reject", None),
    ("B", "ナレッジ管理 ツール 比較", "keep", None),
    ("B", "社内 ナレッジ 共有 ツール", "merge", "ナレッジ管理 ツール 比較"),
    ("B", "Reclaim.ai 使い方", "reject", None),
    ("B", "チーム コミュニケーション ツール 比較", "reject", None),
    ("B", "Asana 料金", "reject", None),
    ("B", "Notion 使い方", "reject", None),
    ("B", "業務可視化 ツール", "keep", None),
    ("B", "バックオフィス 効率化 ツール", "keep", None),
    ("B", "バックオフィス 効率化 AI", "merge", "バックオフィス 効率化 ツール"),
    ("B", "テレワーク 業務効率化 ツール", "merge", "業務効率化 ツール おすすめ"),
    ("C", "ノーコード ツール 比較", "reject", None),
    ("C", "ノーコード ツール おすすめ", "reject", None),
    ("C", "ノーコード 業務自動化", "merge", "業務自動化 ツール おすすめ"),
    ("C", "業務自動化 ツール おすすめ", "keep", None),
    ("C", "業務自動化 ツール 比較", "merge", "業務自動化 ツール おすすめ"),
    ("C", "業務自動化 ツール 無料", "keep", None),
    ("C", "Make 使い方", "keep", None),
    ("C", "Make 日本語", "keep", None),
    ("C", "Make 代替", "reject", None),
    ("C", "Zapier 使い方", "reject", None),
    ("C", "Zapier 代替", "keep", None),
    ("C", "Zapier Make 比較", "merge", "Zapier 代替"),
    ("C", "Make n8n 比較", "keep", None),
    ("C", "n8n 使い方", "keep", None),
    ("C", "n8n 料金", "keep", None),
    ("C", "n8n セルフホスト", "keep", None),
    ("C", "Power Automate 使い方", "reject", None),
    ("C", "Power Automate 料金", "reject", None),
    ("C", "RPA ツール 比較", "merge", "RPA おすすめ"),
    ("C", "RPA 事例", "keep", None),
    ("C", "RPA 中小企業", "merge", "RPA おすすめ"),
    ("C", "RPA ノーコード 違い", "keep", None),
    ("C", "RPA 費用", "merge", "RPA おすすめ"),
    ("C", "iPaaS 比較", "reject", None),
    ("C", "Slack 自動化", "keep", None),
    ("C", "Google スプレッドシート 自動化", "keep", None),
    ("C", "Gmail 自動化 ツール", "reject", None),
    ("C", "AI エージェント 業務自動化", "keep", None),
    ("C", "業務自動化 事例", "keep", None),
    ("C", "ChatGPT 業務 自動化", "merge", "AI 業務効率化"),
    ("A", "Fireflies 使い方", "keep", None),
    ("A", "Fireflies 料金", "keep", None),
    ("A", "Fireflies 日本語", "keep", None),
    ("A", "Krisp 使い方", "keep", None),
    ("A", "Krisp 料金", "keep", None),
    ("A", "Otter 日本語", "reject", None),
    ("A", "Zoom 議事録 自動", "keep", None),
    ("A", "Google Meet 議事録 自動", "keep", None),
    ("A", "Teams 議事録 自動", "keep", None),
    ("A", "オンライン 会議 議事録 自動化", "merge", "AI 議事録 おすすめ"),
    ("A", "議事録 要約 AI", "keep", None),
    ("A", "議事録 ツール 比較", "merge", "AI 議事録 おすすめ"),
    ("A", "議事録 ツール 無料", "merge", "AI 議事録 無料"),
    ("A", "文字起こし ツール 無料", "reject", None),
    ("A", "文字起こし ソフト 精度", "reject", None),
    ("A", "会議 効率化 ツール", "keep", None),
    ("A", "会議 効率化 方法", "reject", None),
    ("A", "Descript 使い方", "reject", None),
    ("A", "Descript 料金", "reject", None),
    ("A", "Notta 料金", "reject", None),
    ("A", "Rimo Voice 料金", "reject", None),
    ("A", "議事録 AI 精度 比較", "merge", "AI 議事録 おすすめ"),
    ("A", "会議 録音 文字起こし アプリ", "reject", None),
    ("A", "議事録 自動作成 AI 無料", "merge", "AI 議事録 無料"),
    ("D", "生成AI 社内 導入", "merge", "生成AI 法人 導入"),
    ("D", "生成AI 導入 事例", "keep", None),
    ("D", "生成AI 導入 ステップ", "merge", "生成AI 法人 導入"),
    ("D", "生成AI 社内 ルール", "keep", None),
    ("D", "生成AI ガイドライン 企業", "merge", "生成AI 社内 ルール"),
    ("D", "生成AI セキュリティ 対策 企業", "keep", None),
    ("D", "ChatGPT Team 料金", "merge", "ChatGPT 法人 プラン"),
    ("D", "ChatGPT Enterprise 料金", "merge", "ChatGPT 法人 プラン"),
    ("D", "ChatGPT 法人 プラン", "keep", None),
    ("D", "Microsoft Copilot 法人 料金", "keep", None),
    ("D", "Copilot 導入", "merge", "Microsoft Copilot 法人 料金"),
    ("D", "Gemini for Workspace 料金", "keep", None),
    ("D", "Claude 法人 利用", "reject", None),
    ("D", "RAG 社内 導入", "merge", "社内 ChatGPT 構築"),
    ("D", "社内 ChatGPT 構築", "keep", None),
    ("D", "生成AI 業務 活用 事例", "merge", "生成AI 導入 事例"),
    ("D", "生成AI 営業 活用", "merge", "営業 AI ツール"),
    ("D", "生成AI 研修 法人", "keep", None),
    ("D", "生成AI 導入 補助金", "keep", None),
    ("D", "生成AI 導入 費用", "keep", None),
    ("D", "AI 業務効率化 事例", "merge", "業務効率化 ツール 事例"),
    ("E", "CRM 比較", "merge", "CRM おすすめ"),
    ("E", "CRM おすすめ", "keep", None),
    ("E", "CRM 無料", "keep", None),
    ("E", "中小企業 CRM", "merge", "CRM おすすめ"),
    ("E", "SFA CRM 違い", "keep", None),
    ("E", "SFA 比較", "merge", "CRM おすすめ"),
    ("E", "SFA おすすめ", "merge", "CRM おすすめ"),
    ("E", "HubSpot 料金", "keep", None),
    ("E", "HubSpot 使い方", "keep", None),
    ("E", "HubSpot 無料", "merge", "HubSpot 料金"),
    ("E", "HubSpot 代替", "keep", None),
    ("E", "Pipedrive 料金", "keep", None),
    ("E", "Pipedrive 使い方", "keep", None),
    ("E", "営業 自動化 ツール", "keep", None),
    ("E", "営業 管理 ツール", "merge", "CRM おすすめ"),
    ("E", "顧客管理 ツール 比較", "merge", "CRM おすすめ"),
    ("E", "顧客管理 ツール 無料", "merge", "CRM 無料"),
    ("E", "マーケティングオートメーション 比較", "keep", None),
    ("E", "MA ツール 比較", "merge", "マーケティングオートメーション 比較"),
    ("E", "ActiveCampaign 料金", "keep", None),
    ("E", "ActiveCampaign 使い方", "reject", None),
    ("E", "リード 管理 ツール", "keep", None),
    ("E", "営業 AI ツール", "keep", None),
    ("E", "インサイドセールス ツール", "keep", None),
    ("E", "Salesforce 代替", "keep", None),
    ("E", "Salesforce 料金", "reject", None),
    ("E", "Zoho CRM 料金", "reject", None),
    ("E", "メール 配信 ツール 比較", "reject", None),
    ("E", "営業 メール 自動化", "keep", None),
    ("E", "顧客管理 エクセル", "reject", None),
)
